addons:
    ssh_known_hosts: c4dtsrv1.epfl.ch

stages:
    - lint
    - build
    - name: deploy
      if: branch = master

jobs:
    include:
        - stage: lint
          name: webapp
          language: node_js
          node_js: 10
          install: cd webapp && npm ci
          script: ng lint

        - stage: build
          name: webapp
          language: go
          go: 1.12.x
          script: make webapp-build
          before_install:
              - sudo apt-get install -y protobuf-compiler
          addons:
              apt:
                  update: true

notifications:
    email: false
