addons:
    ssh_known_hosts: c4dtsrv1.epfl.ch

stages:
    - lint
    - build
    - name: deploy
      if: branch = master

jobs:
    include:
        - stage: lint
          name: webapp
          language: node_js
          node_js: 10
          install: cd webapp && npm ci
          script: ng lint

        - stage: build
          name: webapp
          language: go
          go: 1.12.x
          script: make webapp-build
          before_install:
              - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip -O /tmp/protoc.zip
              - unzip /tmp/protoc.zip -d /tmp bin/protoc
              - export PATH=${PATH}:/tmp/bin

notifications:
    email: false
