version: "3"

services:
  conode-1:
    image: ghcr.io/c4dt/service-stainless-backend:latest
    build:
      context: backend
    volumes:
      - ./backend/build/conode-1:/config
    network_mode: host
    command: "-d 2 -c /config/private.toml server"
    environment:
      - CONODE_SERVICE_PATH=/config
      - DEBUG_COLOR=true

  conode-2:
    image: ghcr.io/c4dt/service-stainless-backend:latest
    build:
      context: backend
    network_mode: host
    volumes:
      - ./backend/build/conode-2:/config
    command: "-d 2 -c /config/private.toml server"
    environment:
      - CONODE_SERVICE_PATH=/config
      - DEBUG_COLOR=true

  conode-3:
    image: ghcr.io/c4dt/service-stainless-backend:latest
    build:
      context: backend
    network_mode: host
    volumes:
      - ./backend/build/conode-3:/config
    command: "-d 2 -c /config/private.toml server"
    environment:
      - CONODE_SERVICE_PATH=/config
      - DEBUG_COLOR=true

  conode-4:
    image: ghcr.io/c4dt/service-stainless-backend:latest
    build:
      context: backend
    network_mode: host
    volumes:
      - ./backend/build/conode-4:/config
    command: "-d 2 -c /config/private.toml server"
    environment:
      - CONODE_SERVICE_PATH=/config
      - DEBUG_COLOR=true

  demo:
    image: ghcr.io/c4dt/service-stainless-webapp:latest
    build:
      context: webapp
    network_mode: host
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./webapp/src/assets:/webapp/assets
