version: "3"

services:
  conode-1:
    image: ghcr.io/c4dt/service-stainless-persistent:latest
    volumes:
      - ./backend/configs/conode-1:/config
    ports:
      - "7772-7779:7772-7779"
    environment:
      - NODE_NBR=1
      - DEBUG_COLOR=true

  conode-2:
    image: ghcr.io/c4dt/service-stainless-persistent:latest
    volumes:
      - ./backend/configs/conode-2:/config
    environment:
      - NODE_NBR=2
      - DEBUG_COLOR=true
    network_mode: service:conode-1

  conode-3:
    image: ghcr.io/c4dt/service-stainless-persistent:latest
    volumes:
      - ./backend/configs/conode-3:/config
    environment:
      - NODE_NBR=3
      - DEBUG_COLOR=true
    network_mode: service:conode-1

  conode-4:
    image: ghcr.io/c4dt/service-stainless-persistent:latest
    volumes:
      - ./backend/configs/conode-4:/config
    environment:
      - NODE_NBR=4
      - DEBUG_COLOR=true
    network_mode: service:conode-1

  demo:
    image: ghcr.io/c4dt/service-stainless-webapp:latest
    ports:
      - "8080:8080"
