name: Build and push Docker image, deploy on target

on:
  push:
    branches:
      - master
  pull_request:
    branches:

jobs:
  build:
    name: "Test, build and push Docker image, deploy on c4dtsrv1"
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Lint
        run: |
          cd webapp
          npm ci
          ng lint
