name: Build and push Docker image, create release

env:
  DEPLOY_USER: stainless
  DEPLOY_HOST: c4dtsrv1.epfl.ch

on:
  push:
    branches:
      - master
  pull_request:
    branches:

jobs:
  build:
    name: "Test, build and push Docker image, deploy on c4dtsrv1"
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "10"

      - name: Lint TypeScript
        run: |
          cd webapp
          npm ci
          npx ng lint

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Lint Go
        run: |
          cd backend
          if test $( gofmt -d . | tee gofmt.results | wc -l ) -ne 0; then cat gofmt.results; exit 1; fi
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...

      - name: Setup protobuf C compiler
        uses: arduino/setup-protoc@v1
        with:
          version: "3.19"

      - name: Test
        run: |
          make backend-test
          make backend-serve-test
          make webapp-test

      - name: Build
        run: |
          make webapp-build

      - name: Push Docker image
        if: github.event_name == 'push'
        run: >
          docker login
          --username ${{ secrets.DOCKER_USERNAME }}
          --password ${{ secrets.DOCKER_PASSWORD }} &&
          docker push c4dt/service-stainless-backend:latest

      - name: Prepare artifact
        if: github.event_name == 'push'
        run: |
          tar -C ./webapp --xz --create --file dist.tar.xz  --exclude '*.toml' ./dist

      - name: Create release
        id: create_release
        if: github.event_name == 'push'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          title: "Development build"
          files: |
            dist.tar.xz
