name: Build docker
on:
  push:

jobs:
  # This is copied from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build requirements
        run: |
          sudo apt install -y protobuf-compiler
          rm -rf backend/{configs,build}
          make configs webapp-proto
          git config --global user.name "Build Workflow"
          git config --global user.email "build_workflow@users.noreply.github.com"
          git add backend/configs
          git commit -am "Configs generated on $( date )"
          git push

      - name: Build and push Docker image for nodes
#        id: build-and-push-backend
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ghcr.io/c4dt/service-stainless-backend:latest

      - name: Build and push Docker image
#        id: build-and-push-webapp
        uses: docker/build-push-action@v4
        with:
          context: webapp
          push: true
          tags: ghcr.io/c4dt/service-stainless-webapp:latest
